import './category.dart';

var dummy_category = [
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar1.png",
    userName: "Calum Lewis",
    itemImagePath: "assets/images/img_home1.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar2.png",
    userName: "Eilif Sonas",
    itemImagePath: "assets/images/img_home2.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar3.png",
    userName: "Elena Shelby",
    itemImagePath: "assets/images/img_home3.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar4.png",
    userName: "John Priyadi",
    itemImagePath: "assets/images/img_home4.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar1.png",
    userName: "Calum Lewis",
    itemImagePath: "assets/images/img_home1.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar2.png",
    userName: "Eilif Sonas",
    itemImagePath: "assets/images/img_home2.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar3.png",
    userName: "Elena Shelby",
    itemImagePath: "assets/images/img_home3.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar4.png",
    userName: "John Priyadi",
    itemImagePath: "assets/images/img_home4.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar1.png",
    userName: "Calum Lewis",
    itemImagePath: "assets/images/img_home1.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar2.png",
    userName: "Eilif Sonas",
    itemImagePath: "assets/images/img_home2.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar3.png",
    userName: "Elena Shelby",
    itemImagePath: "assets/images/img_home3.png",
    itemName: "Pancake",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
  CategoryItem(
    userAvatarPath: "assets/images/img_avatar4.png",
    userName: "John Priyadi",
    itemImagePath: "assets/images/img_home4.png",
    itemName: "Salad",
    itemDescription: "Food  ♦  > 60 mins",
    isFavorite: false,
  ),
];
